language: python
python:
  - "3.9"
  - "3.8"
install:
  - "pip install -r requirements.txt"
script:
  - python -m pytest src/test/
  - python -m doctest -v src/*.py
  - python -m bandit -qr src/interfaces/
  - python -m bandit -q src/*.py