language: python
python:
  - "3.9"
  - "3.8"
install:
  - "pip install -r requirements-travis.txt"
script:
  - python -m pytest tests/
  - python -m doctest -v *.py
  - python -m bandit -qr implementation/
  - python -m bandit -q *.py