language: python
python:
  - "3.9"
  - "3.8"
install:
  - "pip install -r requirements.txt"
script:
  - python -m pytest test/
  - python -m doctest -v *.py
  - python -m bandit -qr interfaces/
  - python -m bandit -q *.py