language: python
python:
  - "3.9"
  - "3.8"
install:
  - "pip install -r requirements.txt"
script:
  - cd src && python -m pytest src/test/
  - cd src && python -m doctest -v src/*.py
  - cd src && python -m bandit -qr interfaces/
  - cd src && python -m bandit -q *.py